version: "3"
services:
  api:
    image: book-shop
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8866:8867"
    networks:
      - host
networks:
  host:
